---
title: "Time-dependent Quantum Problems (1d)"
author: "efefer"
format:
  revealjs:
    smaller: true
    scrollable: true
---

## Time-dependent Schroedinger equation (TDSE)

$$
\imath \hbar \frac{\partial}{\partial t} \Psi_{\mathrm{S}}(t) = H \Psi_{\mathrm{S}}(t)
$$

Formal solution can be obtained using _time evolution operator_:
$$
U(t) = \mathrm{e}^{-\imath H t/\hbar}
$$
which maps $\Psi_{\mathrm{S}}(0)$  ke $\Psi_{\mathrm{S}}(t)$.

Operator evolusi ini sendiri memenuhi Persamaan Schroedinger bergantung-waktu:
Time evolution operator also satisfies TDSE:
$$
\imath \hbar \dot{U}(t) = H U(t)
$$
with initial condition $U(0) = 1$.


## Time propagation using finite-difference

Discretize time using temporal grid points: $t = i\Delta t$

Use forward difference approximation to first derivative wrt time:
$$
\frac{\partial \Psi}{\partial t} = \frac{\Psi(t + \Delta t) - \Psi(t)}{\Delta t}
$$
or centered difference:
$$
\frac{\partial \Psi}{\partial t} = \frac{\Psi(t + \Delta t) - \Psi(t - \Delta t)}{2\Delta t}
$$

Apply these to TDSE, we obtain, for example, in case of centered difference:
$$
\imath \hbar \frac{\partial}{\partial t} \Psi(t) = H \Psi(t) 
$$
We obtain the following scheme:
$$
\Psi(t + \Delta t) = -2 \imath \Delta t H \Psi(t) + \Psi(t - \Delta t) + \mathcal{O}(\Delta t^3)
$$
This is an explicit scheme, given information of $\Psi$ at two previous time points.

What about backward difference? We will obtain an implicit scheme.


## Free Gaussian wave packet

Hamiltonian:
$$
H_{0} = -\frac{h^2}{2m} \frac{\mathrm{d}^2}{\mathrm{d}x^2}
$$

Free-particle eigenstates:
$$
\frac{1}{2\pi} \mathrm{e}^{\imath \left[kx - \omega(k) t \right]}
$$

$$
\omega(k) = E(k) = \frac{k^2}{2m}
$$

The wave packet is defined as:
$$
\psi(x,t) = \frac{1}{2\pi} \int_{-\infty}^{\infty} A(k) \, 
\mathrm{e}^{\imath \left[kx - \omega(k) t \right]} \, \mathrm{d}k
$$

For a Gaussian wave packet the amplitude is defined as
$$
A(k) = \left( \frac{1}{\sigma\sqrt{\pi}} \right)^{1/2}
\exp\left[ -\frac{(k - k_0)^2}{2\sigma^2} \right]
$$

Integrating over $k$ we obtain:
$$
\psi(x,t) = \left( \frac{\sigma}{\sqrt{\pi}(1 + \imath \Omega t)} \right)^{1/2}
\exp\left[ -\frac{\sigma^2}{2} \frac{(x - vt)^2}{1 + \imath \Omega t} \right]
\exp\left[ \imath k_0 (x - vt) \right]
$$
where:
$v = \hbar k_0/m$ and $\Omega = \hbar \sigma^2/m$

For $t = 0$
$$
\psi(x,0) = \left( \frac{\sigma}{\sqrt{\pi}} \right)^{1/2}
\underbrace{\exp\left[ -\frac{\sigma^2}{2}x^2 \right]}_{\text{Gaussian}}
\underbrace{\exp\left[\imath k_0 x\right]}_{\text{plane wave}}
$$
A Gaussian modulated with plane wave


Probability distribution of the Gaussian wave packet:
$$
\left| \psi(x,t) \right|^2 =
\frac{\sigma}{\sqrt{\pi}(1 + \Omega^2 t^2)}
\exp\left[
  -\sigma^2 \frac{(x - vt)^2}{(1 + \Omega^2 t^2)}
\right]
$$


## Crank-Nicolson method

$$
\mathrm{e}^{\imath H \Delta t/\hbar} \approx
\left( 1 + \frac{\imath \Delta t}{2\hbar} \right)^{-1}
\left( 1 - \frac{\imath \Delta t}{2\hbar} \right) 
$$

$$
\psi(t + \Delta t) =
\left( 1 + \frac{\imath \Delta t}{2\hbar} \right)^{-1}
\left( 1 - \frac{\imath \Delta t}{2\hbar} \right) \psi(t)
$$


## Tannor, Ch 02, Free-particle wavepacket

$V(x) = 0$

$$
H = -\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2}
$$

The spatial factor, $\psi(x)$, of the particular solution must satisfy
the equation
$$
H \psi(x) = E \psi(x)
$$

The eigenfunctions and eigenvalues are:
$$
\begin{align}
\psi(x) & = \mathrm{e}^{\pm \imath k x} \\
E & = \frac{\hbar^2 k^2}{2m} = \frac{p^2}{2m}
\end{align}
$$

We have defined $p = \hbar k$ based on the analogy to the classical
expression for kinetic energy
$$
E_{\mathrm{cl}} = \frac{1}{2} m v_{\mathrm{cl}}^2 =
\frac{p_{\mathrm{cl}}^2}{2m}
$$

Note that the eigenvalues for a continuous spectrum, there is
a physically acceptable solution for every value of $k$ (and
every positive value of $E$).

Combining the spatial and temporal factors we obtain the particular
solution:
$$
\begin{align}
\Psi(x,t) & = \mathrm{e}^{\imath k x} \mathrm{e}^{-\imath Et/\hbar} \\
& = \mathrm{e}^{\imath\left( kx - Et/\hbar \right)} \\
& = \exp\left[ \imath\left( kx - \frac{\hbar k^2}{2m} t \right) \right]
\end{align}
$$

##

We discuss some of static features of $\Psi(x,t)$ in the context of
wave equations in general.

First, we fix $t$ and vary $x$.
Note that we will have the same value at $x_2$ and $x_1$ if
$$
k(x_2 - x_1) = n2\pi
$$
Choosing $n = 1$ gives a unique definition of wavelength:
$$
\lambda = x_2 - x_1
$$
and therefore
$$
k\lambda = 2\pi
$$
or
$$
k = \frac{2\pi}{\lambda}
$$

Thus, $k$ characterizes the the number of radians (which is $2\pi$ times the
number of cycles) per unit distance.

$k$ is called the _wavenumber_

The definition of a wavenumber is a property of the solutions of any
wave equation; what is unique to the Schroedinger equation is that
$p = \hbar k = h/\lambda$.
This is the de Broglie relationship that preceded wave mechanics.
Its physical significance is that the momentum proportional to the density
of spatial oscillations, that is, number of oscillations per unit length.

##

We now fix $x$ and vary $t$.

We note that any wave of the form $\mathrm{e}^{\imath \omega t}$ will
have the same value at $t_2$ and $t_1$ if
$$
\omega(t_2 - t_1) = n2\pi
$$

Choosing $n = 1$ defines the fundamental period:
$$
\tau = t_2 - t_1
$$
and thus
$$
\omega \tau = 2\pi
$$

$\omega$ characterizes the number of radians per unit time, and
is called the _angular frequency_; it is a factor of $2\pi$ larger
than frequency $\nu$, defined by:
$$
\nu = \frac{1}{\tau}
$$

Again, the definition of an angular frequency is a property of the solutions
of any wave equation; what is unique to the Schroedinger equation is that
$$
E = \hbar \omega = h \nu
$$

This relation is due to Einstein and also preceded wave mechanics by many years.

##

Note that for free particle:
$$
\omega(k) = \frac{\hbar k^2}{2m}
$$
there is a simple functional relation between $\omega$ and $k$.

This functional relationship is known as the _dispersion_ relation.

As in other wave equations, the dispersion relation $\omega(k)$
determines both the _phase velocity_ and _group velocity_ of the wave:
$$
\begin{align}
\text{phase velocity} & = \frac{\omega}{k} \\
\text{group velocity} & = \frac{\partial\omega}{\partial k}
\end{align}
$$

It is the specific functional relationship between $\omega$ and $k$ that
distinguish between the motion of quantum waves from other waves that
occur in nature.

##

Concept of phase velocity, rewrite the particular solution
$$
\begin{align}
\Psi(x,t) & = \exp\left[ \imath \left( x - \frac{\hbar k}{2m} t \right) \right] \\
& = \exp\left[ \imath \left( x - v t \right) \right]
\end{align}
$$

As long as the quantity $x - vt = 0$ we can change the values of $x$ and $t$
to obtain a constant value of the wave amplitude.
This leads to the condition $x = vt$. Since $x$ increases as $t$ increases,
$\Psi(x,t)$ is a wave traveling to the right with a velocity
$$
v = \frac{\hbar k}{2m} = \frac{\omega}{k}
$$
called the _phase velocity_.

Since the momentum of the wavepacket, $p$, is equal to $\hbar k$,
the phase velocity is $p/2m$, which is one-half the classical expression
for the velocity.

To obtain the classical behavior, we need to use a wavepacket and examine
its _group velocity_.

##

The general solution for free-particle wavepacket:
$$
\Psi(x,t) = \int_{-\infty}^{\infty} a(k)
\exp\left[ \imath \left( x - \frac{\hbar k}{2m} t \right) \right]
\, \mathrm{d}k
$$

The function $a(k)$ may be found from the $t = 0$ wavepacket through
the use of Fourier theorem. At $t = 0$ the wavepacket is
$$
\Psi(x,t) = \int_{-\infty}^{\infty} a(k) \mathrm{e}^{\imath k x}\, \mathrm{d}k
$$
Multiplying both sides by $\exp(-\imath k' x)$, integrating over $x$, and
using the property of Dirac delta function:
$$
\int_{-\infty}^{\infty} \mathrm{e}^{-\imath k' x} \mathrm{e}^{\imath k x} \, \mathrm{d}x =
2\pi \delta(k - k')
$$
we find that:
$$
a(k) = \frac{1}{2\pi} \int_{-\infty}^{\infty} \Psi(x,0) \mathrm{e}^{-\imath k x} \mathrm{d}x
$$

##

Rewrite:
$$
\Psi(x,t) = \int_{-\infty}^{\infty} a(k,t) \mathrm{e}^{\imath kx} \, \mathrm{d}k
$$
with definition
$$
a(k,t) = a(k) \mathrm{e}^{-\imath \frac{hk^2}{2m}t}
$$
We find that
$$
a(k,t) = \frac{1}{2\pi} \int_{-\infty}^{\infty} \Psi(x,t) \mathrm{e}^{-\imath k x} \mathrm{d}x
$$

We will refer to $a(k,t)$ as the $k$-_representation_ of the wavefunction. 

## Exercise 2.1

(Part a)

Show that if $\Psi(x,0)$ is normalized it follows that
$$
\int_{-\infty}^{\infty} a^{*}(k,t) a(k,t) \, \mathrm{d}k =
\int_{-\infty}^{\infty} a^{*}(k) a(k) = \frac{1}{2\pi}
$$

(Part b)

Combine the result of (Part a) with Eq. 2.18 to show that if $\Psi(x,0)$
is normalized so is $\Psi(x,t)$.

## Center of the wavepacket

Consider the time evolution of the center of the wavepacket
$$
\langle x \rangle_{t} =
\frac{\int_{-\infty}^{\infty} \Psi^{*}(x,t) \, x \, \Psi(x,t) \, \mathrm{d}x }
{\int_{-\infty}^{\infty} \Psi^{*}(x,t) \Psi(x,t) \, \mathrm{d}x} 
$$

Using the fact that in the $k$-representation the position operator
$\hat{x}$ is given by:
$$
\hat{x} = \imath \frac{\partial}{\partial k}
$$

Final result:
$$
\langle x \rangle_{t} = \frac{\langle p \rangle t}{m} +
\langle x \rangle_{0}
$$

Defining the group velocity, $v_g$ as the velocity of the center
of the wavepacket we find that
$$
v_g = \frac{\mathrm{d}\langle x \rangle_{t}}{\mathrm{d}t} =
\frac{\langle p \rangle}{m}
$$
which is the analog of the classical relation
$v_{\mathrm{cl}} = \frac{p_{\mathrm{cl}}}{m}$.

We see that for free particle the group velocity is independent of time,
as in classical mechanics, and is completely determined by the
distribution $a(k)$ at $t = 0$.

That the correspondence between classical and quantum mechanics in Eq. 2.24
survives for an arbitrary distribution of $a(k)$ is
surprising and represents a special case of Ehrenfest's theorem.